### ISSUE TITLE
Todo list.

### ISSUE THREAD

**Issue by lesander** [nognooitmeegemaakt/website#1]
#### Must haves
- [x] 20pts Mobile navbar.
- [x] 10pts Landing page proper scaling and header.
- [x] 40pts Add content for all groups.
- [x] 30pts Add content for contact page.
- [x] 10pts Add content for agenda page.
- [x] 50pts Add Facebook automated web hook to update news file.
- [x] 30pts Fix mobile navbar dropdown.
- [x] 50pts Scaling: Switch to `em`s, remove all `px` in css for scalability.
- [x] 20pts Fix scrolling on homepage for small desktop screens.
- [x] **99pts Redesign group pages.**
#### Should haves
- [x] 30pts Open news items in full screen black div.
- [x] 10pts Add favicon.
- [x] 50pts Add Photos of each group on the group page.
- [x] 50pts Design a new mobile menu.
- [x] 30pts Implement Shave.js in news items.
- [x] 99pts Add Agenda and Group CMS for users.
#### Could haves
- [x] 40pts Add print agenda button to agenda pages.
- [ ] 20pts Add Like on Facebook button on News page.
- [ ] 20pts Add 404 page.
- [ ] Use smaller images for speltak-picker.
- [ ] Add 'volunteer' page.
- [x] Make 'jaarplanner' visible.
